export const CATEGORIES = [
  "Single Sound Cracker",
  "Ground Chakkars",
  "Fancy Ground Chakkars",
  "Flower Pot",
  "Fancy Flower Pot",
  "Twinkling Stars",
  "Candles",
  "Fancy Candles",
  "Toys & Sprinklers",
  "Bijili Crackers",
  "Kids Special Fancy",
  "Spl Fancy Fountains",
  "Peacock Series",
  "Kids Toys Fountain",
  "Multistep Toys Fountain",
  "Atom Bomb",
  "Paper Bomb",
  "Rockets Mini Aerial",
  "Night Mega Aerial Fancy",
  "Lovely Inf & Ayyan Special Fancy Series",
  "Special Dual Fancy Series",
  "Aerial Repeating Shots",
  "Festival Display Shots",
  "New Arrival Fancy",
  "Festival Mega Display Shots Garlands",
  "Colour Matches Ring Caps and Gun Toys",
  "Sparklers",
];