export const CATEGORIES = [
  "Sparklers",
  "Flower Pot",
  "Fancy Flower Pot",
  "Ground Chakkars",
  "Fancy Ground Chakkars",
  "Single Sound Cracker",
  "Rockets",
  "Mini Aerial",
  "Atom Bomb",
  "Paper Bomb",
  "Bijili Crackers",
  "Twinkling Stars",
  "Toys & Sprinklers",
  "Kids Special Fancy fountains",
  "Spl Fancy Fountains",
  "Peacock Series",
  "Kids Toys Fountain",
  "spl Multistep Toys Fountain",
  "Night Mega Aerial Fancy",
  "Lovely Inf & Ayyan Special Fancy Series",
  "Special Dual Fancy Series lovely.inf",
  "Aerial Repeating Shots",
  "Festival Display Shots",
  "New Arrival fantastic aerials",
  "Festival Mega Display Shots ",
  "Ring Caps and Gun Toys",
  "Garlands",
  "Colour Matches",
  "Candles",
  "Fancy Candles",
];